# Generated by Django 3.0.4 on 2020-03-11 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('style', models.TextField(max_length=30)),
                ('abv', models.DecimalField(decimal_places=1, max_digits=3)),
                ('bitterness', models.IntegerField()),
                ('datebrewed', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Keg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(max_length=15)),
                ('dateupdated', models.DateField()),
                ('beer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kegs.Beer')),
            ],
        ),
    ]
