# Generated by Django 3.0.4 on 2020-03-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='description',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keg',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
